export const IpcChannel = {
  windowMinimize: "window:minimize",
  windowMaximize: "window:maximize",
  windowClose: "window:close",
  windowIsMaximized: "window:isMaximized",
  projectsList: "projects:list",
  projectsCreate: "projects:create",
  projectsUpdate: "projects:update",
  projectsRemove: "projects:remove",
  conversationsList: "conversations:list",
  conversationsCreate: "conversations:create",
  conversationsRemove: "conversations:remove",
  conversationsExport: "conversations:export",
  conversationsGetBranchLabels: "conversations:getBranchLabels",
  conversationsSetBranchLabel: "conversations:setBranchLabel",
  conversationsSetTags: "conversations:setTags",
  searchQuery: "search:query",
  spendCapsGet: "spendCaps:get",
  spendCapsSet: "spendCaps:set",
  healthSummary: "health:summary",
  costsAggregate: "costs:aggregate",
  debugGetLatest: "debug:getLatest",
  messagesList: "messages:list",
  messagesCreate: "messages:create",
  messagesUpdate: "messages:update",
  messagesActivate: "messages:activate",
  settingsGetAppearance: "settings:getAppearance",
  settingsSetAppearance: "settings:setAppearance",
  settingsGetSession: "settings:getSession",
  settingsSetSession: "settings:setSession",
  providersList: "providers:list",
  secretsList: "secrets:list",
  secretsSave: "secrets:save",
  secretsRemove: "secrets:remove",
  secretsTest: "secrets:test",
  chatSend: "chat:send",
  chatAbort: "chat:abort",
  chatEvent: "chat:event",
  chatPreviewPacket: "chat:previewPacket",
} as const;

export type IpcChannelName = (typeof IpcChannel)[keyof typeof IpcChannel];
